function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stairs x
%  Y1:  stairs y

%  Auto-generated by MATLAB on 27-Jan-2020 09:13:03

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stairs
stairs(X1,Y1,'MarkerFaceColor',[1 0 0],'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',10,...
    'Marker','o',...
    'LineWidth',3,...
    'LineStyle','-.',...
    'Color',[0 0 1]);

box(axes1,'on');
